baseURL = 'https://jmd28.github.io/'
languageCode = 'en-gb'
theme = 'salinger'

title = "james diffley."
copyright = 'james diffley'
ignoreErrors = ["error-remote-getjson"]

[params]
DateFormat = " 8 January 2006"

author = "james diffley"
description = "software engineer | portfolio with quick links to useful places"
header = "<strong>james diffley. </strong>"
keywords = ["Portfolio", "developer", "coding", "maker"]
showHeaderOnHomepage = true
#googleAnalytics = ""
twemoji = true
text404 = "Since the page you were looking for seems like doesn't exist, we <strong>strongly</strong> suggest you to better investigate the URL and/or go back to the <a href=\"/\">home</a>." #</br></br> <iframe src=\"https://giphy.com/embed/aCKMaeduKfFXG\" width=\"480\" height=\"480\" frameBorder=\"0\" class=\"giphy-embed\" allowFullScreen></iframe>"
#fontawesomekitcode = ""


[permalinks]
'/' = '/:slug/'
'projects' = '/:slug/'

[[params.social]]
name = "github"
url = "https://github.com/jmd28"
icon = "fa fa-github"
before = "Check out my "

[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/jamesdiffley28"
icon = "fa fa-linkedin"
before = "and "

[[params.social]]
name = "email"
icon = "fa fa-envelope"
url = "mailto:jamesdiffley28@gmail.com"
before = ", or contact me by"

# [[params.social]]
# name = "email"
# icon = "fa fa-telegram"
# url = "https://t.me/john"
# before = "and on "
# after = "."


[Menu]
[[Menu.Main]]
name = "projects."
url = "/projects/"
weight = 1

[[Menu.Main]]
name = "cv."
url = "/CV.pdf"
weight = 3


[[Menu.Main]]
name = "contact me."
url = "mailto:jamesdiffley28@gmail.com"
weight = 2

[taxonomies]
tag = "tags"
category = "categories"


[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
